### ISSUE TITLE
FPS Problem

### ISSUE THREAD

**Issue by eugenelawrence** [wuhuikai/SparseMask#1]
I notice that you have implemented a fast segmentation model. I wonder how you evaluate the FPS with pytorch.
If you evaluate FPS with the code of your previous project FastFCN [https://github.com/wuhuikai/FastFCN/blob/master/experiments/segmentation/test_fps_params.py](https://github.com/wuhuikai/FastFCN/blob/master/experiments/segmentation/test_fps_params.py), it is wrong. 
Please refer to [https://github.com/wutianyiRosun/CGNet/issues/2](https://github.com/wutianyiRosun/CGNet/issues/2) for more information.

**Comment by wuhuikai** [comment]
In our experiment, the difference between results with and without `torch.cuda.synchronize()` is less than 1 FPS.
